name: Build

on:
    push:
    pull_request:

env:
    PRIMARY_NODEJS_VERSION: 16

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup node ${{ env.PRIMARY_NODEJS_VERSION }}
              uses: actions/setup-node@v2
              with:
                node-version: ${{ env.PRIMARY_NODEJS_VERSION }}
                cache: "npm"
            - run: npm ci
            - run: npm run lint

    test-bundle:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup node ${{ env.PRIMARY_NODEJS_VERSION }}
              uses: actions/setup-node@v2
              with:
                node-version: ${{ env.PRIMARY_NODEJS_VERSION }}
                cache: "npm"
            - run: npm ci
            - run: npm run bundle-and-test
              env:
                REPORTER: "min"

    run-tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
                node_version:
                    - 12.20.0
                    - 14.13.0
                    - 16

        steps:
            - uses: actions/checkout@v2
            - name: Setup node ${{ matrix.node_version }}
              uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node_version }}
                cache: "npm"
            - run: npm ci
            - run: npm run test
              env:
                REPORTER: "min"
            - run: npm run esm-to-cjs-and-test
              env:
                REPORTER: "min"

            - run: npm run coverage
              if: ${{ matrix.node_version == env.PRIMARY_NODEJS_VERSION }}
            - name: Coveralls parallel
              if: ${{ matrix.node_version == env.PRIMARY_NODEJS_VERSION }}
                uses: coverallsapp/github-action@1.1.3
                with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                flag-name: node-${{ matrix.node_version }}
                parallel: true

  send-to-coveralls:
    needs: run-tests
    runs-on: ubuntu-latest
    name: Send coverage to Coveralls
    steps:
    - name: Send coverage to Coveralls
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true